name: build-runner

on:
  push:
    branches: ["main"]
    paths: ["htest-runner/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Change directory
      run: cd ./htest-runner
      
    - name: Build
      run: mvn -B deploy
